#!/bin/bash
TAG=abcdnet_v12
CONFIG=configs/vbsvvh_semimerged_finalrun_correctsigfiles_150lamda_24sep_remove_xwqq.json
MODEL=/home/users/eslam.zenhom/public_html/uf_work/vbs2/abcdnet/vbsvvh_semimerged_finalrun_correctsigfiles_150lamda_24sep_remove_xwqq/models/vbsvvh_semimerged_finalrun_correctsigfiles_150lamda_24sep_remove_xwqq_modelLeakyNeuralNetwork_nhidden3_hiddensize64_lrConstantLR0.001_discolambda150_epoch300_model.pt
python3 scripts/infer_ucsd.py $CONFIG $MODEL --baby_glob="/home/users/eslam.zenhom/public_html/uf_work/vbs2/analysis/studies/vbsvvhjets_semimerged/output_${TAG}*/Run2"
